### ISSUE TITLE
Invert camera mouse control, or even make it optional to change it

### ISSUE THREAD

**Issue by Gordon-Dry** [4c65736975/shopExtension#2]
The default mouse control is exactly opposite to the normal behaviour of the mouse control ingame.
Please fix it and optionally add a setting to change it.

**Comment by 4c65736975** [comment]
The mouse control is set to be comfortable and intuitive, I do not plan to add an option to change it (it is unnecessary and there would be too many options in the UI)

**Comment by Gordon-Dry** [comment]
It's not comfortable and intuitive if it's exact the opposite of the normal ingame behaviour.
It's more likely coercion.
Any sane player who want to change that will be happy to find such a setting.
**But the setting is even not needed if it's just fixed to be normal.**

**Comment by 4c65736975** [comment]
The camera movement in the first-person view is the same as in the third-person view. It is intuitive for me and I think also for other players, because no one told me that it is different, quite the opposite.

**Comment by Gordon-Dry** [comment]
Ingame, sitting inside a vehicle, 1st person:
Mouse movement to the right, view turns right

Store, after pressing C:
While clicking the left mouse button, mouse movement to the left, view turns right

And everything vice versa.
